### ISSUE TITLE
Textures bug in cars

### ISSUE THREAD

**Issue by valanhol** [pudingus/mafia-4ds-import-export#1]
Hi, thanks for your hard work. I used your plugin for 3ds max 2021, the models unload well, but there is a small bug in the textures of the cars. Is it fixable?

https://drive.google.com/file/d/1tAHSSy2Ls1Zffa9ATncy-TMx89fm9C6z/view?usp=sharing

**Comment by pudingus** [comment]
Hi, this is a problem with transparent textures that use color keying instead of alpha channel, since there is no native support for it in 3ds Max. I see this is not good for rendering. I don't know how to solve this yet, maybe with custom shader or converting it to alpha map. I will look into it more

**Comment by pudingus** [comment]
This is partially fixed in c4f0cb7
It displays correctly in the viewport (best displayed with Stochastic transparency) and using the Scanline renderer, but not yet with the Arnold renderer, since it doesn't support Standard material which is the 4ds Material based on.
Scanline:
![scanline](https://user-images.githubusercontent.com/39903631/89101300-03acd100-d3ff-11ea-8ba1-9163479c71e7.png)

Arnold:
![arnold](https://user-images.githubusercontent.com/39903631/89101303-0c9da280-d3ff-11ea-8f30-9aaf32af5c05.png)

**Comment by valanhol** [comment]
v-ray understands the alpha channel. I haven't checked the version of this fix, but I did the same as you did in the code, only manually through Photoshop (created an alpha channel) and it works.

**Comment by valanhol** [comment]
Thanks for doing!
